### ISSUE TITLE
Will throw exception when used in a UWP compiled with .net native

### ISSUE THREAD

**Issue by NPadrutt** [liveservices/LiveSDK-for-Windows#59]
I use LiveSDK in a [UWP ](https://github.com/Apply-Solutions/MoneyManager). When I add the lib manually it works nicely. But only if I deactivated .net native. Otherwise it will crash. The exceptions logged aren't really helpful, eg:

```C#
at MoneyManager.Windows!<BaseAddress>+0xbd7629
   at MoneyManager.Windows!<BaseAddress>+0xbd7b4d
   at MoneyManager.Windows!<BaseAddress>+0x8311d9
   at MoneyManager.Windows!<BaseAddress>+0x82896d
   at MoneyManager.Windows!<BaseAddress>+0xc23fef
   at MoneyManager.Windows!<BaseAddress>+0xc23e15
   at MoneyManager.Windows!<BaseAddress>+0xc141fb
   at MoneyManager.Windows!<BaseAddress>+0xc140b3
   at MoneyManager.Windows!<BaseAddress>+0xc13bb3
   at MoneyManager.Windows!<BaseAddress>+0xc246d3
   at MoneyManager.Windows!<BaseAddress>+0xa2dcb3
   at System.Dynamic.ConvertBinder.Bind(Dynamic.DynamicMetaObject target, Dynamic.DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.ParameterExpression> parameters, Linq.Expressions.LabelTarget returnLabel)
   at MoneyManager.Windows!<BaseAddress>+0x8c6bc7
   at MoneyManager.Windows!<BaseAddress>+0x8b306f
   at MoneyManager.Windows!<BaseAddress>+0xa2a25f
   at MoneyManager.Windows!<BaseAddress>+0xa2a02d
   at MoneyManager.Windows!<BaseAddress>+0xc31b31
   at MoneyManager.Windows!<BaseAddress>+0xc319d1
   at MoneyManager.Windows!<BaseAddress>+0xc31c71
   at MoneyManager.Windows!<BaseAddress>+0x7ffced
   at MoneyManager.Windows!<BaseAddress>+0x7ffba3
   at MoneyManager.Windows!<BaseAddress>+0x6d5087
   at System.Func<System.Action<System.Runtime.CompilerServices.CallSite,System.Object,System.Object>>.Invoke()
   at MoneyManager.Windows!<BaseAddress>+0x98a017
--- End of stack trace from previous location where exception was thrown ---
   at MoneyManager.Windows!<BaseAddress>+0x775989
   at MoneyManager.Windows!<BaseAddress>+0x775ccd
   at MoneyManager.Windows!<BaseAddress>+0x81da49
   at MoneyManager.Windows!<BaseAddress>+0x81d9e9
   at MoneyManager.Windows!<BaseAddress>+0x81d9cb
   at MoneyManager.Windows!<BaseAddress>+0x98ae4b
--- End of stack trace from previous location where exception was thrown ---
   at MoneyManager.Windows!<BaseAddress>+0x775989
   at MoneyManager.Windows!<BaseAddress>+0x775ccd
   at MoneyManager.Windows!<BaseAddress>+0x98cecd
```

**Comment by NPadrutt** [comment]
This seems to work with the VS Tools for UWP 1.1. Therefore I close this issue.
